// Demo tour for share-link visitors: a small dismissible "how to try this demo" card (3–5 steps, each may link to a
// page). Generated by the LLM from the plan + the project's pages, editable by the owner. Stored per project.
import fs from 'node:fs';
import path from 'node:path';
import { projectDir, readProject } from './registry.js';
import { chat } from './llm.js';
import { logUsage } from './usagelog.js';
import { normalizeUsage } from './agent.js';

const file = id => path.join(projectDir(id), '.superdemo', 'tour.json');

export function getTour(id) {
  try { return normalizeTour(JSON.parse(fs.readFileSync(file(id), 'utf8'))); } catch { return null; }
}

export function normalizeTour(t = {}) {
  const steps = (Array.isArray(t.steps) ? t.steps : []).slice(0, 6).map(s => ({
    text: String(s?.text ?? s ?? '').trim().slice(0, 120),
    page: String(s?.page || '').trim().replace(/^\/+/, '').replace(/^https?:.*$/, '').slice(0, 80), // relative page only
  })).filter(s => s.text);
  return { enabled: t.enabled !== false, title: String(t.title || '怎么体验这个 Demo').trim().slice(0, 40), intro: String(t.intro || '').trim().slice(0, 160), steps };
}

export function saveTour(id, t) {
  const tour = normalizeTour(t);
  fs.mkdirSync(path.dirname(file(id)), { recursive: true });
  fs.writeFileSync(file(id), JSON.stringify(tour, null, 1));
  return tour;
}

/** Pages for the step editor's dropdown: { page: '' for the home page | 'x.html', title }. */
export function pageOptions(id) {
  const dir = path.join(projectDir(id), 'public');
  try {
    return fs.readdirSync(dir).filter(f => f.endsWith('.html')).slice(0, 20).map(f => {
      const html = fs.readFileSync(path.join(dir, f), 'utf8');
      const title = ((html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i) || [])[1] || (html.match(/<title>([^<]*)<\/title>/i) || [])[1] || '').replace(/<[^>]+>/g, '').trim().slice(0, 30);
      return { page: f === 'index.html' ? '' : f, title: title || f };
    }).sort((a, b) => (a.page === '') ? -1 : (b.page === '') ? 1 : 0);
  } catch { return [{ page: '', title: '首页' }]; }
}

/** HTML pages of the project with their <title> / first <h1>, for the generator. */
function pages(id) {
  const dir = path.join(projectDir(id), 'public');
  const out = [];
  try {
    for (const f of fs.readdirSync(dir).filter(f => f.endsWith('.html')).slice(0, 12)) {
      const html = fs.readFileSync(path.join(dir, f), 'utf8');
      const title = (html.match(/<title>([^<]*)<\/title>/i) || [])[1] || '';
      const h1 = ((html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i) || [])[1] || '').replace(/<[^>]+>/g, '').trim();
      out.push(`${f === 'index.html' ? '（首页）' : f}：${[title, h1].filter(Boolean).join(' / ')}`);
    }
  } catch {}
  return out;
}

export async function generateTour(id) {
  const p = readProject(id);
  if (!p) throw new Error('project not found');
  const plan = p.plan;
  const context = [
    `项目：${p.name}`, `需求：${p.description || ''}`,
    plan?.summary && `目标：${plan.summary}`,
    plan?.flows?.length && `关键流程：\n${plan.flows.map(f => '- ' + f).join('\n')}`,
    plan?.highlights?.length && `演示亮点：\n${plan.highlights.map(f => '- ' + f).join('\n')}`,
    `页面：\n${pages(id).join('\n') || '（只有首页）'}`,
  ].filter(Boolean).join('\n\n');
  const r = await chat({ thinking: false, temperature: 0.4, messages: [
    { role: 'system', content: `你为一个 Web Demo 写「访客导览」：第一次打开的人看到一张小卡片，按步骤体验最有价值的功能。只输出 JSON：{"title":"不超过12字","intro":"一句话说明这个 Demo 帮谁解决什么，不超过40字","steps":[{"text":"动作 + 能看到什么，不超过40字，如：在「库存总览」看哪些商品标红缺货","page":"对应页面文件名，如 dashboard.html；首页留空"}]}，3-5 步，按体验顺序，用业务语言，不提技术。` },
    { role: 'user', content: context },
  ] });
  const u = normalizeUsage(r.usage);
  if (u) logUsage({ p: id, i: u.input, o: u.output, c: u.cached });
  const text = String(r.message.content || '').replace(/^```(?:json)?\s*|\s*```$/g, '');
  let json; try { json = JSON.parse(text.slice(text.indexOf('{'), text.lastIndexOf('}') + 1)); } catch { throw new Error('导览生成失败，请重试'); }
  return saveTour(id, { ...json, enabled: true });
}

/** Visitor card script (shadow DOM, shown until dismissed; remembered per link in localStorage). */
export function tourScript(tour, token) {
  const data = JSON.stringify({ t: tour.title, i: tour.intro, s: tour.steps, k: 'sdTour:' + token }).replace(/</g, '\\u003c');
  return `(function(){var d=${data};try{if(localStorage.getItem(d.k))return;}catch(e){}
var base=location.pathname.replace(/^(\\/s\\/[^/]+\\/).*/,'$1');
var host=document.createElement('div');host.style.cssText='position:fixed;left:16px;bottom:16px;z-index:2147483001';var r=host.attachShadow({mode:'open'});
function esc(s){return String(s).replace(/[&<>"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}
r.innerHTML='<style>*{box-sizing:border-box;font:14px/1.55 system-ui,-apple-system,"PingFang SC","Microsoft YaHei",sans-serif}'
+'.c{width:min(340px,calc(100vw - 32px));background:#fff;color:#1f2430;border-radius:14px;box-shadow:0 12px 40px rgba(0,0,0,.22);padding:14px 16px;border:1px solid #e6e8ee}'
+'h4{margin:0 0 2px;font-size:15px}p{margin:0 0 8px;color:#6b7280;font-size:13px}ol{margin:0;padding-left:20px}li{margin:4px 0}a{color:#3b6cf6;text-decoration:none}a:hover{text-decoration:underline}'
+'.x{position:absolute;right:8px;top:6px;border:0;background:none;font-size:18px;color:#9ca3af;cursor:pointer}.f{display:flex;justify-content:flex-end;margin-top:8px}.f button{border:0;background:#3b6cf6;color:#fff;border-radius:8px;padding:6px 14px;cursor:pointer}'
+'@media (max-width:600px){.c{font-size:13px}}</style>'
+'<div class="c"><button class="x" aria-label="关闭">×</button><h4>👋 '+esc(d.t)+'</h4>'+(d.i?'<p>'+esc(d.i)+'</p>':'')
+'<ol>'+d.s.map(function(s){return '<li>'+(s.page?'<a href="'+esc(base+s.page)+'">'+esc(s.text)+'</a>':esc(s.text))+'</li>';}).join('')+'</ol>'
+'<div class="f"><button class="ok">开始体验</button></div></div>';
function close(){host.remove();try{localStorage.setItem(d.k,'1');}catch(e){}}
r.querySelector('.x').onclick=close;r.querySelector('.ok').onclick=close;
(document.body||document.documentElement).appendChild(host);})();`;
}
